[files]
extend-exclude = ["CHANGELOG.md"]
ignore-hidden = true
ignore-vcs = true
ignore-dot = true

[default]
check-filename = true
check-file = true
locale = "en"
binary = false
unicode = true
extend-ignore-re = [
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]
extend-ignore-identifiers-re = []
extend-ignore-words-re = []

[default.extend-words]

actix = "actix"
anyhow = "anyhow"
axum = "axum"
bincode = "bincode"
bitflags = "bitflags"
clippy = "clippy"
dashmap = "dashmap"
dotenvy = "dotenvy"
egui = "egui"
flate2 = "flate2"
futures = "futures"
itertools = "itertools"
miette = "miette"
miri = "miri"
nextest = "nextest"
proptest = "proptest"
rayon = "rayon"
reqwest = "reqwest"
rhai = "rhai"
rustacean = "rustacean"
rustc = "rustc"
rustdoc = "rustdoc"
rustfmt = "rustfmt"
rustup = "rustup"
serde = "serde"
sqlx = "sqlx"
tauri = "tauri"
thiserror = "thiserror"
tokio = "tokio"
tracing = "tracing"
wasm = "wasm"
wgpu = "wgpu"
winit = "winit"

amqp = "amqp"
avro = "avro"
bson = "bson"
clickhouse = "clickhouse"
cors = "cors"
csrf = "csrf"
grpc = "grpc"
jwks = "jwks"
jwt = "jwt"
kafka = "kafka"
msgpack = "msgpack"
nats = "nats"
ndjson = "ndjson"
oidc = "oidc"
otel = "otel"
protobuf = "protobuf"
sse = "sse"
webhook = "webhook"
websocket = "websocket"
websockets = "websockets"

ebpf = "ebpf"
epoll = "epoll"
grafana = "grafana"
ioctl = "ioctl"
jaeger = "jaeger"
kqueue = "kqueue"
kubernetes = "kubernetes"
libc = "libc"
mmap = "mmap"
musl = "musl"
nginx = "nginx"
postgres = "postgres"
postgresql = "postgresql"
prometheus = "prometheus"
ptrace = "ptrace"
redis = "redis"
sqlite = "sqlite"
xattr = "xattr"
zstd = "zstd"


[type.proto]
extend-glob = ["*.proto"]
check-file = false
