max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

hard_tabs = false
tab_spaces = 4
merge_derives = true
remove_nested_parens = true


edition = "2024"
style_edition = "2024"

reorder_imports = true
reorder_modules = true
